name: CI/CD – exdev-apply-api

on:
  push:
    branches: ["master"]
  workflow_dispatch: {}    # permite correrlo manualmente

permissions:
  contents: read
  packages: write

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image (:latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/ianbattistoni/exdev-apply-api:latest  # todo en minúsculas

      - name: Deploy over SSH (only master)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            APP_DIR=/opt/exdev-apply-api
            REPO=IanBattistoni/exdev-apply-api

            
            if [ ! -d "$APP_DIR/.git" ]; then
              rm -rf "$APP_DIR"
              mkdir -p "$APP_DIR"
              git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$REPO "$APP_DIR"
            else
              git -C "$APP_DIR" fetch --all
              git -C "$APP_DIR" checkout -B master origin/master
            fi

            
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker compose -f "$APP_DIR/docker-compose.yml" pull
            docker compose -f "$APP_DIR/docker-compose.yml" up -d --remove-orphans
            docker image prune -f